sadonsclub/bookings/urls.py
from django.urls import path

from . import views


app_name = 'bookings'

urlpatterns = [
    path('', views.booking, name='booking'),
    path('computer_booking/<int:computer_id>/', views.computer_booking, name='computer_booking'),
    path(
        'computer_booking/<int:computer_id>/confirm_booking',
        views.confirm_booking,
        name='confirm_booking'
    )
]

sadonsclub/club/urls.py
from django.urls import path

from . import views

app_name = 'club'

urlpatterns = [
    path('', views.IndexPageTemplateView.as_view(), name='index'),
    path('about/', views.AboutPageTemplateView.as_view(), name='about')
]

sadonsclub/sadonsclub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('club.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls')),
    path('booking/', include('bookings.urls'))
]

sadonsclub/bookings/models.py
from django.db import models

from datetime import timedelta

MAX_LENGTH_CHARFIELD = 256


class Category(models.Model):
    category_name = models.CharField(
        max_length=MAX_LENGTH_CHARFIELD
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.category_name


class Computers(models.Model):
    booking = models.BooleanField(
        default=False,
        verbose_name='Забронирован'
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Рабочий'
    )
    category = models.ForeignKey(
        Category,
        null=True,
        on_delete=models.SET_NULL,
        related_name='category'
    )

    class Meta:
        verbose_name = 'компьютер'
        verbose_name_plural = 'Компьютеры'

    def __str__(self):
        return f'{self.category.category_name} №{self.pk}'


class Bookings(models.Model):
    computer_id = models.ForeignKey(
        Computers,
        null=True,
        on_delete=models.SET_NULL
    )
    username = models.ForeignKey(
        'users.CustomUsers',
        null=True,
        on_delete=models.SET_NULL
    )
    booking_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата и время бронирования'
    )
    booked_from = models.TimeField(
        verbose_name='Дата начала бронирования'
    )
    booked_until = models.TimeField(
        verbose_name='Дата окончания бронирования'
    )
    booked_to_date = models.DateField(
        verbose_name='Дата предстоящего бронирования'
    )
    status = models.BooleanField(
        default=True,
        verbose_name='Статус'
    )

    class Meta:
        verbose_name  = 'бронирование'
        verbose_name_plural = 'Бронирования'
    
    def __str__(self):
        return f'{self.pk}'

sadonsclub/bookings/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView
from datetime import time

from .models import Computers, Bookings

from users.models import CustomUsers



def booking(request):
    context = {
        'computers_standart': Computers.objects.filter(
            category__category_name='Standart'
        ),
        'computers_vip': Computers.objects.filter(
            category__category_name='VIP'
        ),
        'computers_premium': Computers.objects.filter(
            category__category_name='Premium'
        )
    }
    return render(request, 'bookings/booking.html', context)


def computer_booking(request, computer_id):
    date_now = timezone.now().date().isoformat()
    bookings_computer = Bookings.objects.filter(
        computer_id=computer_id,
        status=True
    ).values(
        'booked_from',
        'booked_until'
    )
    busy_hours = []
    for booking in bookings_computer:
        busy_hours.append(booking['booked_from'].hour)
        busy_hours.append(booking['booked_until'].hour)
    available_times = [time(hour=x) for x in range(24) if x not in busy_hours]
    return render(
        request,
        'bookings/computer_booking.html',
        context={
            'id': computer_id,
            'today': date_now,
            'available_times': available_times,
        }
    )


def confirm_booking(request, computer_id):
    if request.method == 'POST':
        booked_from = request.POST.get('start_time')
        booked_until = request.POST.get('end_time')
        booking_date = request.POST.get('booking_date')
        user = CustomUsers.objects.get(username=request.user.username)
        computer = get_object_or_404(
            Computers,
            id=computer_id
        )
        Bookings.objects.create(
            computer_id=computer,
            username=user,
            booked_from=booked_from,
            booked_until=booked_until,
            booked_to_date=booking_date
        )
    return render(
        request,
        'bookings/confirm_booking.html',
        context={
            'id': computer_id,
            'booking'
            'booked_from': booked_from,
            'booked_until': booked_until,
        }
    )

sadonsclub/templates/bookings/booking.html
{% extends 'base.html' %}
{% block title %}
    Бронирование
{% endblock %}
{% block name_page %}
    Бронирование
{% endblock %}
{% block content %}
<!-- Standart -->
<div class="text-center mt-2">
    <h3>Standart</h3>
</div>
<div class="container mt-5">
    <div class="row">
        {% for computer in computers_standart %}
            {% if computer.is_active %}
                <a href='{% url "bookings:computer_booking" computer.id %}' class="btn btn-success mx-2">Компьютер № {{ computer.id }}</a>
            {% else %}
                <a href='#' class="btn btn-danger mx-2">№ {{ computer.id }} - На ремонте</a>
            {% endif %}
        {% endfor %}
    </div>
</div>
<!-- VIP -->
<div class="text-center mt-2">
    <h3>VIP</h3>
</div>
<div class="container mt-5">
    <div class="row">
        {% for computer in computers_vip %}
            {% if computer.is_active %}
                <a href='{% url "bookings:computer_booking" computer.id %}' class="btn btn-success mx-2">Компьютер № {{ computer.id }}</a>
            {% else %}
                <a href='#' class="btn btn-danger mx-2">№ {{ computer.id }} - На ремонте</a>
            {% endif %}
        {% endfor %}
    </div>
</div>
<!-- Premium -->
<div class="text-center mt-2">
    <h3>Premium</h3>
</div>
<div class="container mt-5">
    <div class="row">
        {% for computer in computers_premium %}
            {% if computer.is_active %}
                <a href='{% url "bookings:computer_booking" computer.id %}' class="btn btn-success mx-2">Компьютер № {{ computer.id }}</a>
            {% else %}
                <a href='#' class="btn btn-danger mx-2">№ {{ computer.id }} - На ремонте</a>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

sadonsclub/templates/bookings/computer_booking.html
{% extends 'base.html' %}
{% block name_page %}
    Подтверждение
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<div class="container text-center mt-5">
    <h2>Забронировать компьютер № {{ id }}</h2>
    <form method="POST" action="{% url 'bookings:confirm_booking' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="bookingDate">Выберите дату бронирования:</label>
            <input type="date" id="bookingDate" name="booking_date" class="form-control" required min="{{ today }}" value="{{ today }}">
        </div>
        <div class="form-group">
            <label for="startTime">Выберите время начала бронирования:</label>
            <select id="startTime" name="start_time" class="form-control" required>
                <option value="">Выберите время</option>
                {% for time in available_times %}
                    <option value="{{ time }}">{{ time }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group">
            <label for="endTime">Выберите время конца бронирования:</label>
            <select id="endTime" name="end_time" class="form-control" required>
                <option value="">Выберите время</option>
                {% for time in available_times %}
                    <option value="{{ time }}">{{ time }}</option>
                {% endfor %}
            </select>
        </div>
            <button type="submit" class="btn btn-success mt-4">Забронировать</button>
            <a href="{% url 'bookings:booking' %}" class="btn btn-secondary mt-4">Вернуться на страницу бронирования</a>
        </div>
    </form>
{% else %}
<div class="container">
    <div class="input-group">
        <span class="input-group-text">Ваше имя и фамилия</span>
        <input type="text" aria-label="First name" class="form-control">
        <input type="text" aria-label="Last name" class="form-control">
      </div>
</div>
{% endif %}
{% endblock %}

sadonsclub/templates/bookings/confirm_booking.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="h1 text-center text-white">
                Успешно забронирован компьютер {{ id }}
            </div>
		</div>
	</div>
</div>
{% endblock %}