sadonsclub/club/urls.py
from django.urls import path

from . import views

app_name = 'club'

urlpatterns = [
    path('', views.IndexPageTemplateView.as_view(), name='index'),
    path('about/', views.AboutPageTemplateView.as_view(), name='about')
]

sadonsclub/sadonsclub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('club.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls')),
    path('booking/', include('bookings.urls'))
]

sadonsclub/users/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import CreateView


from . import views
from .forms import RegistrationForm

app_name = 'user'

urlpatterns = [
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=RegistrationForm,
            success_url=reverse_lazy('club:index')
        ),
        name='register'
    ),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('my_bookings/', views.my_bookings, name='my_bookings'),
    path('settings/', views.user_settings, name='settings')
]

sadonsclub/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>
    {% block title %}
    {% endblock %}
</title>
<!-- Stylesheets -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">

<link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
<link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
</head>

<body>
    <div class="preloader">
        <div class="icon">

        </div>
    </div>
    {% include 'includes/header.html' %}
    {% if request.path != '/' %}
        <section class="page-banner" style="background-image:url({% static 'images/background/2.jpg' %});">
            <div class="auto-container">
                <div class="inner-container clearfix">
                    <h1>
                        {% block name_page %}
                        {% endblock %}
                    </h1>
                </div>
            </div>
        </section>
        <main>
    {% endif %}
    {% block content %}
    {% endblock %}
    </main>
    {% include 'includes/footer.html' %}


<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/appear.js' %}"></script>
<script src="{% static 'js/wow.js' %}"></script>
<script src="{% static 'js/scrollbar.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

sadonsclub/templates/register.html
{% extends 'base.html' %}
{% block content %}
<section class="page-banner" style="background-image:url(images/background/title-bg.jpg);">
    <div class="auto-container">
        <div class="inner-container clearfix">
            <h1>Регистрация</h1>
        </div>
    </div>
</section>
<section class="text-center">
    <main class="form-signin w-100 m-auto">
        <form method="POST" action="{% url 'user:register' %}">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Регистрация</h1>
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    <input type="{{ field.field.widget.input_type }}" 
                           name="{{ field.name }}" 
                           id="{{ field.id_for_label }}" 
                           class="form-control" 
                           value="{{ field.value|default_if_none:'' }}">
                    {% for error in field.errors %}
                        <div class="alert alert-danger mt-1">{{ error }}</div>
                    {% endfor %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                </div>
            {% endfor %}
            <button class="btn btn-primary w-100 py-2" type="submit">Регистрация</button>
        </form>
        <a href="{% url 'user:login' %}" class="btn btn-secondary w-100 py-2 mt-3">Вход в аккаунт</a>
    </main>
</section>

{% endblock %}