sadonsclub/bookings/urls.py
from django.urls import path

from . import views


app_name = 'bookings'

urlpatterns = [
    path('', views.booking, name='booking'),
    path('computer_booking/<int:computer_id>/', views.computer_booking, name='computer_booking'),
    path(
        'computer_booking/<int:computer_id>/confirm_booking',
        views.confirm_booking,
        name='confirm_booking'
    )
]

sadonsclub/club/urls.py
from django.urls import path

from . import views

app_name = 'club'

urlpatterns = [
    path('', views.IndexPageTemplateView.as_view(), name='index'),
    path('about/', views.AboutPageTemplateView.as_view(), name='about')
]

sadonsclub/sadonsclub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('club.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls')),
    path('booking/', include('bookings.urls'))
]

sadonsclub/users/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import CreateView


from . import views
from .forms import RegistrationForm

app_name = 'user'

urlpatterns = [
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=RegistrationForm,
            success_url=reverse_lazy('club:index')
        ),
        name='register'
    ),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('my_bookings/', views.my_bookings, name='my_bookings'),
    path('settings/', views.user_settings, name='settings')
]

sadonsclub/templates/includes/footer.html
	{% load static %}
    <!-- Main Footer -->
    <footer class="main-footer">
    	<div class="auto-container">
        	<!--Widgets Section-->
            <div class="widgets-section">
            	<div class="row clearfix">
                	
                    <!--Column-->
                    <div class="column col-lg-4 col-md-6 col-sm-12">
						<div class="footer-widget logo-widget">
							<div class="text">Существует множество вариантов отрывков lorem ipsum, но большинство из них в той или иной форме подверглись изменениям в результате инъекций.</div>
						</div>
					</div>
					
					<!--Column-->
                    <div class="column col-lg-4 col-md-6 col-sm-12">
						<div class="footer-widget links-widget">
							<div class="widget-content">
								<div class="footer-title">
									<h2>Ссылки</h2>
								</div>
								<div class="row clearfix">
									<div class="column col-lg-6 col-md-6 col-sm-12">
										<ul class="list">
											<li><a href="{% url 'club:about' %}">О нас</a></li>
											<li><a href="#">Альбом</a></li>
											<li><a href="#">Связаться с нами</a></li>
										</ul>
									</div>
									<div class="column col-lg-6 col-md-6 col-sm-12">
										<ul class="list">
											<li><a href="#">Help & Support</a></li>
											<li><a href="#">Privacy Policy</a></li>
											<li><a href="#">Terms of Use</a></li>
										</ul>
									</div>
								</div>
							</div>	
						</div>
					</div>
					
					<!--Column-->
                    <div class="column col-lg-4 col-md-6 col-sm-12">
						<div class="footer-widget newsletter-widget">
							<div class="footer-title">
                            	<h2>Получать рассылку</h2>
                            </div>
							<div class="text">Подпишитесь на нас, чтобы получать последние новости и обновления</div>
							<div class="newsletter-form">
                                <form method="post" action="contact.html">
                                    <div class="form-group clearfix">
                                        <input type="email" name="email" value="" placeholder="Email address" required>
                                        <button type="submit" class="theme-btn newsletter-btn"><span class="fas fa-envelope"></span></button>
                                    </div>
                                </form>
                            </div>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<!-- Footer Bottom -->
		<div class="footer-bottom">
			<div class="auto-container">
				<!--Scroll to top-->
				<div class="scroll-to-top scroll-to-target" data-target="html"><span class="flaticon-up-arrow"></span></div>
				<!--Scroll to top-->
				<div class="row clearfix">
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<div class="copyright">&copy; Copyrights, 2024 All Rights Reserved</div>
					</div>
					<!-- Column -->
					<div class="column col-lg-6 col-md-12 col-sm-12">
						<ul class="social-icons">
							<li><a href="#"><span class="fab fa-twitter"></span></a></li>
							<li><a href="#"><span class="fab fa-facebook-square"></span></a></li>
							<li><a href="#"><span class="fab fa-pinterest-p"></span></a></li>
							<li><a href="#"><span class="fab fa-instagram"></span></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		
	</footer>

sadonsclub/templates/includes/header.html
   {% load static %}
   <!-- Main Header -->
    <header class="main-header">
        <!-- Header Top -->
        <div class="header-top">
            <div class="auto-container clearfix">

                <div class="top-right">
                    <ul class="social-icons">
                        <li><a href="https://vk.com/id143658507"><span class="fab fa-vk"></span></a></li>
                        <li><a href="#"><span class="fab fa-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Header Upper -->
        <div class="header-upper">
            <div class="inner-container">
                <div class="auto-container clearfix">
                    <!--Logo-->
                    <div class="logo-outer">
                        <div class="logo"><a href="{% url 'club:index' %}"><img src="{% static 'images/logo.png' %}" alt="" title="SadOnsClub"></a></div>
                    </div>

                    <!--Nav Box-->
                    <div class="nav-outer clearfix">
                        <!--Mobile Navigation Toggler-->
                        <div class="mobile-nav-toggler"><span class="icon flaticon-menu-1"></span></div>

                        <!-- Main Menu -->
                        <nav class="main-menu navbar-expand-md navbar-light">
                            <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                                <ul class="navigation clearfix pull-left">
                                    <li><a href="{% url 'club:index' %}">Главная страница</a></li>
									<li><a href="{% url 'club:about' %}">О нас</a></li>
                                    <li><a href="gallery.html">Альбом</a></li>
                                </ul>
                                <ul class="navigation pull-right clearfix">
                                    <li><a href="{% url 'bookings:booking' %}">Бронирование</a></li>
                                    <li><a href="contact.html">Связаться с нами</a></li>
                                    {% if user.is_authenticated %}
									<li class="dropdown"><a href="{% url 'user:profile' %}">{{ user.username }}</a>
                                        <ul>
                                            <li><a href="{% url 'user:profile' %}">Профиль</a></li>
                                            <li><a href="{% url 'user:my_bookings' %}">Мои бронирования</a></li>
											<li><a href="{% url "user:settings" %}">Настройки</a></li>
                                            <form method="POST" action="{% url 'logout' %}">
                                                {% csrf_token %}
											    <button type="submit" class="nav-link" style="background: none; border: none; color: inherit; cursor: pointer;">Выйти</button>
                                            </form>
                                        </ul>
                                    </li>
                                    {% else %}
                                    <li><a href="{% url 'login' %}">Войти</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </nav>
                        <!-- Main Menu End-->
                    </div>
                </div>
            </div>
        </div>
        <!--End Header Upper-->

        <!-- Sticky Header  -->
        <div class="sticky-header">
            <div class="auto-container clearfix">
                <!--Logo-->
                <div class="logo pull-left">
                    <a href="{% url 'club:index' %}" title=""><img src="{% static 'images/logo.png' %}" alt="" title=""></a>
                </div>
                <!--Right Col-->
                <div class="pull-right">
                    <!-- Main Menu -->
                    <nav class="main-menu clearfix">
                        <!--Keep This Empty / Menu will come through Javascript-->
                    </nav><!-- Main Menu End-->
                </div>
            </div>
        </div><!-- End Sticky Menu -->

        <!-- Mobile Menu  -->
        <div class="mobile-menu">
            <div class="menu-backdrop"></div>
            <div class="close-btn"><span class="icon flaticon-close"></span></div>
            
            <nav class="menu-box">
                <div class="nav-logo"><a href="{% url 'club:index' %}"><img src="{% static 'images/logo.png' %}" alt="" title=""></a></div>
                <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
				<!--Social Links-->
				<div class="social-links">
					<ul class="clearfix">
						<li><a href="#"><span class="fab fa-vk"></span></a></li>
						<li><a href="#"><span class="fab fa-instagram"></span></a></li>

					</ul>
                </div>
            </nav>
        </div><!-- End Mobile Menu -->
    </header>
    <!-- End Main Header -->